In [3]:
import csv
import pandas as pd
import numpy as np
import sklearn
import matplotlib

In [4]:
orders = pd.read_csv(r'/Users/jaycohen/Documents/NYCDSA/Homework/Machine_Learning_Lab/MLlab/Jay/data/Orders.csv')

In [7]:
## Problem 1

orders.loc[:,'Profit'] = orders.loc[:,'Profit'].str.replace(',','')
orders.loc[:,'Profit'] = orders.loc[:,'Profit'].str.replace('$','')
orders.loc[:,'Sales'] = orders.loc[:,'Sales'].str.replace(',','')
orders.loc[:,'Sales'] = orders.loc[:,'Sales'].str.replace('$','')

In [9]:
orders.loc[:,'Profit'] = pd.to_numeric(orders.loc[:,'Profit'])
orders.loc[:,'Sales'] = pd.to_numeric(orders.loc[:,'Sales'])

In [10]:
orders

,Row.ID,Order.ID,Order.Date,Ship.Date,Ship.Mode,Customer.ID,Customer.Name,Segment,Postal.Code,City,...,Product.ID,Category,Sub.Category,Product.Name,Sales,Quantity,Discount,Profit,Shipping.Cost,Order.Priority
0,40098,CA-2014-AB10015140-41954,11/11/14,11/13/14,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,221.98,2,0.0,62.15,40.770,High
1,26341,IN-2014-JR162107-41675,2/5/14,2/7/14,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.40,9,0.1,-288.77,923.630,Critical
2,25330,IN-2014-CR127307-41929,10/17/14,10/18/14,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.17,9,0.1,919.97,915.490,Medium
3,13524,ES-2014-KM1637548-41667,1/28/14,1/30/14,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless",2892.51,5,0.1,-96.54,910.160,Medium
4,47221,SG-2014-RH9495111-41948,11/5/14,11/6/14,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.96,8,0.0,311.52,903.040,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2015-KE1642066-42174,6/19/15,6/19/15,Same Day,KE-1642066,Katrina Edelman,Corporate,NaN,Kure,...,OFF-FA-3072,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.10,5,0.0,4.50,1.010,Medium
51286,34337,US-2014-ZD21925140-41765,5/6/14,5/10/14,Standard Class,ZD-219251408,Zuschuss Donatelli,Consumer,37421.0,Chattanooga,...,FUR-FU-4070,Furniture,Furnishings,"Eldon Image Series Desk Accessories, Burgundy",16.72,5,0.2,3.34,1.930,High
51287,31315,CA-2012-ZD21925140-41147,8/26/12,8/31/12,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,94109.0,San Francisco,...,OFF-AR-5321,Office Supplies,Art,Newell 341,8.56,2,0.0,2.48,1.580,High
51288,9596,MX-2013-RB1979518-41322,2/17/13,2/21/13,Standard Class,RB-1979518,Ross Baird,Home Office,NaN,Valinhos,...,OFF-BI-2919,Office Supplies,Binders,"Acco Index Tab, Economy",13.44,2,0.0,2.40,1.003,Medium
51289,6147,MX-2013-MC1810093-41416,5/22/13,5/26/13,Second Class,MC-1810093,Mick Crebagga,Consumer,NaN,Tipitapa,...,OFF-PA-3990,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.38,3,0.0,1.80,1.002,High

In [19]:
## Problem 2

orders['Order.Date'] = pd.to_datetime(orders['Order.Date'])
orders['Ship.Date'] = pd.to_datetime(orders['Ship.Date'])

In [20]:
orders

,Row.ID,Order.ID,Order.Date,Ship.Date,Ship.Mode,Customer.ID,Customer.Name,Segment,Postal.Code,City,...,Product.ID,Category,Sub.Category,Product.Name,Sales,Quantity,Discount,Profit,Shipping.Cost,Order.Priority
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,221.98,2,0.0,62.15,40.770,High
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.40,9,0.1,-288.77,923.630,Critical
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.17,9,0.1,919.97,915.490,Medium
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless",2892.51,5,0.1,-96.54,910.160,Medium
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.96,8,0.0,311.52,903.040,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2015-KE1642066-42174,2015-06-19,2015-06-19,Same Day,KE-1642066,Katrina Edelman,Corporate,NaN,Kure,...,OFF-FA-3072,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.10,5,0.0,4.50,1.010,Medium
51286,34337,US-2014-ZD21925140-41765,2014-05-06,2014-05-10,Standard Class,ZD-219251408,Zuschuss Donatelli,Consumer,37421.0,Chattanooga,...,FUR-FU-4070,Furniture,Furnishings,"Eldon Image Series Desk Accessories, Burgundy",16.72,5,0.2,3.34,1.930,High
51287,31315,CA-2012-ZD21925140-41147,2012-08-26,2012-08-31,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,94109.0,San Francisco,...,OFF-AR-5321,Office Supplies,Art,Newell 341,8.56,2,0.0,2.48,1.580,High
51288,9596,MX-2013-RB1979518-41322,2013-02-17,2013-02-21,Standard Class,RB-1979518,Ross Baird,Home Office,NaN,Valinhos,...,OFF-BI-2919,Office Supplies,Binders,"Acco Index Tab, Economy",13.44,2,0.0,2.40,1.003,Medium
51289,6147,MX-2013-MC1810093-41416,2013-05-22,2013-05-26,Second Class,MC-1810093,Mick Crebagga,Consumer,NaN,Tipitapa,...,OFF-PA-3990,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.38,3,0.0,1.80,1.002,High

In [25]:
def season_of_date(date):
    year = str(date.year)
    seasons = {'spring': pd.date_range(start=year+'-03-21', end=year+'-06-20'),
               'summer': pd.date_range(start=year+'-06-21', end=year+'-09-22'),
               'autumn': pd.date_range(start=year+'-09-23', end=year+'-12-20')}
    if date in seasons['spring']:
        return 'spring'
    if date in seasons['summer']:
        return 'summer'
    if date in seasons['autumn']:
        return 'autumn'
    else:
        return 'winter'

In [26]:
orders['Season'] = orders['Order.Date'].map(season_of_date)

In [27]:
orders

,Row.ID,Order.ID,Order.Date,Ship.Date,Ship.Mode,Customer.ID,Customer.Name,Segment,Postal.Code,City,...,Category,Sub.Category,Product.Name,Sales,Quantity,Discount,Profit,Shipping.Cost,Order.Priority,Season
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,Technology,Phones,Samsung Convoy 3,221.98,2,0.0,62.15,40.770,High,autumn
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.40,9,0.1,-288.77,923.630,Critical,winter
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.17,9,0.1,919.97,915.490,Medium,autumn
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,Technology,Phones,"Motorola Smart Phone, Cordless",2892.51,5,0.1,-96.54,910.160,Medium,winter
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.96,8,0.0,311.52,903.040,Critical,autumn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2015-KE1642066-42174,2015-06-19,2015-06-19,Same Day,KE-1642066,Katrina Edelman,Corporate,NaN,Kure,...,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.10,5,0.0,4.50,1.010,Medium,spring
51286,34337,US-2014-ZD21925140-41765,2014-05-06,2014-05-10,Standard Class,ZD-219251408,Zuschuss Donatelli,Consumer,37421.0,Chattanooga,...,Furniture,Furnishings,"Eldon Image Series Desk Accessories, Burgundy",16.72,5,0.2,3.34,1.930,High,spring
51287,31315,CA-2012-ZD21925140-41147,2012-08-26,2012-08-31,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,94109.0,San Francisco,...,Office Supplies,Art,Newell 341,8.56,2,0.0,2.48,1.580,High,summer
51288,9596,MX-2013-RB1979518-41322,2013-02-17,2013-02-21,Standard Class,RB-1979518,Ross Baird,Home Office,NaN,Valinhos,...,Office Supplies,Binders,"Acco Index Tab, Economy",13.44,2,0.0,2.40,1.003,Medium,winter
51289,6147,MX-2013-MC1810093-41416,2013-05-22,2013-05-26,Second Class,MC-1810093,Mick Crebagga,Consumer,NaN,Tipitapa,...,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.38,3,0.0,1.80,1.002,High,spring

In [35]:
season_inventory = orders.groupby(['Season','Category'], as_index=False)['Quantity'].sum()

In [36]:
season_inventory

    Season         Category  Quantity
0   autumn        Furniture     11907
1   autumn  Office Supplies     35364
2   autumn       Technology     11592
3   spring        Furniture      7490
4   spring  Office Supplies     24222
5   spring       Technology      7683
6   summer        Furniture      9412
7   summer  Office Supplies     30268
8   summer       Technology      9716
9   winter        Furniture      6083
10  winter  Office Supplies     18390
11  winter       Technology      6185

In [38]:
## Problem 3

returns = pd.read_csv(r'/Users/jaycohen/Documents/NYCDSA/Homework/Machine_Learning_Lab/MLlab/Jay/data/Returns.csv')

In [42]:
returns = returns.rename(columns={"Order ID":"Order.ID"})

In [53]:
returns

     Returned                  Order.ID           Region
0         Yes  CA-2012-SA20830140-41210       Central US
1         Yes  IN-2012-PB19210127-41259     Eastern Asia
2         Yes  CA-2012-SC20095140-41174       Central US
3         Yes    IN-2015-JH158207-42140          Oceania
4         Yes    IN-2014-LC168857-41747          Oceania
...       ...                       ...              ...
1074      Yes   IN-2014-DA1345058-41769    Southern Asia
1075      Yes  US-2013-HG14845140-41530       Eastern US
1076      Yes   US-2013-SJ2021582-41543  Central America
1077      Yes  CA-2015-EB13870140-42269       Eastern US
1078      Yes    EG-2014-PM894038-41846     North Africa

[1079 rows x 3 columns]

In [54]:
returns_full = pd.merge(orders,returns,on='Order.ID',how='inner')

In [55]:
returns_full

,Row.ID,Order.ID,Order.Date,Ship.Date,Ship.Mode,Customer.ID,Customer.Name,Segment,Postal.Code,City,...,Product.Name,Sales,Quantity,Discount,Profit,Shipping.Cost,Order.Priority,Season,Returned,Region_y
0,30191,IN-2012-PB19210127-41259,2012-12-16,2012-12-19,First Class,PB-19210127,Phillip Breyer,Corporate,NaN,Taipei,...,"Lesro Conference Table, with Bottom Storage",1715.16,2,0.0,720.36,725.570,Critical,autumn,Yes,Eastern Asia
1,30190,IN-2012-PB19210127-41259,2012-12-16,2012-12-19,First Class,PB-19210127,Phillip Breyer,Corporate,NaN,Taipei,...,"Safco Classic Bookcase, Pine",2197.50,5,0.0,153.75,627.270,Critical,autumn,Yes,Eastern Asia
2,30187,IN-2012-PB19210127-41259,2012-12-16,2012-12-19,First Class,PB-19210127,Phillip Breyer,Corporate,NaN,Taipei,...,"Lesro Round Table, with Bottom Storage",1356.03,3,0.0,311.85,458.970,Critical,autumn,Yes,Eastern Asia
3,30193,IN-2012-PB19210127-41259,2012-12-16,2012-12-19,First Class,PB-19210127,Phillip Breyer,Corporate,NaN,Taipei,...,"Office Star Swivel Stool, Adjustable",882.15,5,0.0,114.60,203.920,Critical,autumn,Yes,Eastern Asia
4,30189,IN-2012-PB19210127-41259,2012-12-16,2012-12-19,First Class,PB-19210127,Phillip Breyer,Corporate,NaN,Taipei,...,"Okidata Calculator, Red",148.32,3,0.0,68.22,25.480,Critical,autumn,Yes,Eastern Asia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2215,35040,CA-2014-WB21850140-41654,2014-01-15,2014-01-21,Standard Class,WB-218501406,William Brown,Consumer,10011.0,New York City,...,"Square Ring Data Binders, Rigid 75 Pt. Covers,...",49.54,3,0.2,17.34,2.670,Medium,winter,Yes,Eastern US
2216,35038,CA-2014-WB21850140-41654,2014-01-15,2014-01-21,Standard Class,WB-218501406,William Brown,Consumer,10011.0,New York City,...,"#10 Gummed Flap White Envelopes, 100/Box",16.52,4,0.0,7.60,1.690,Medium,winter,Yes,Eastern US
2217,25,US-2013-SJ2021582-41543,2013-09-26,2013-09-29,First Class,SJ-2021582,Sarah Jordon,Consumer,NaN,Hermosillo,...,"Deflect-O Clock, Black",181.12,9,0.4,-75.56,1.085,Medium,autumn,Yes,Central America
2218,36974,CA-2012-ZC21910140-41271,2012-12-28,2013-01-04,Standard Class,ZC-219101402,Zuschuss Carroll,Consumer,60610.0,Chicago,...,Tenex Chairmats For Use with Hard Floors,38.98,3,0.6,-50.67,5.290,Low,winter,Yes,Central US
2219,41315,EG-2014-PM894038-41846,2014-07-26,2014-07-30,Standard Class,PM-894038,Paul MacIntyre,Consumer,NaN,Alexandria,...,"Sanford Pencil Sharpener, Fluorescent",25.83,1,0.0,9.03,1.050,Medium,summer,Yes,North Africa

In [56]:
def year_of_date(date):
    return str(date.year)

In [57]:
returns_full['Year'] = returns_full['Order.Date'].map(year_of_date)

In [58]:
returns_full

,Row.ID,Order.ID,Order.Date,Ship.Date,Ship.Mode,Customer.ID,Customer.Name,Segment,Postal.Code,City,...,Sales,Quantity,Discount,Profit,Shipping.Cost,Order.Priority,Season,Returned,Region_y,Year
0,30191,IN-2012-PB19210127-41259,2012-12-16,2012-12-19,First Class,PB-19210127,Phillip Breyer,Corporate,NaN,Taipei,...,1715.16,2,0.0,720.36,725.570,Critical,autumn,Yes,Eastern Asia,2012
1,30190,IN-2012-PB19210127-41259,2012-12-16,2012-12-19,First Class,PB-19210127,Phillip Breyer,Corporate,NaN,Taipei,...,2197.50,5,0.0,153.75,627.270,Critical,autumn,Yes,Eastern Asia,2012
2,30187,IN-2012-PB19210127-41259,2012-12-16,2012-12-19,First Class,PB-19210127,Phillip Breyer,Corporate,NaN,Taipei,...,1356.03,3,0.0,311.85,458.970,Critical,autumn,Yes,Eastern Asia,2012
3,30193,IN-2012-PB19210127-41259,2012-12-16,2012-12-19,First Class,PB-19210127,Phillip Breyer,Corporate,NaN,Taipei,...,882.15,5,0.0,114.60,203.920,Critical,autumn,Yes,Eastern Asia,2012
4,30189,IN-2012-PB19210127-41259,2012-12-16,2012-12-19,First Class,PB-19210127,Phillip Breyer,Corporate,NaN,Taipei,...,148.32,3,0.0,68.22,25.480,Critical,autumn,Yes,Eastern Asia,2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2215,35040,CA-2014-WB21850140-41654,2014-01-15,2014-01-21,Standard Class,WB-218501406,William Brown,Consumer,10011.0,New York City,...,49.54,3,0.2,17.34,2.670,Medium,winter,Yes,Eastern US,2014
2216,35038,CA-2014-WB21850140-41654,2014-01-15,2014-01-21,Standard Class,WB-218501406,William Brown,Consumer,10011.0,New York City,...,16.52,4,0.0,7.60,1.690,Medium,winter,Yes,Eastern US,2014
2217,25,US-2013-SJ2021582-41543,2013-09-26,2013-09-29,First Class,SJ-2021582,Sarah Jordon,Consumer,NaN,Hermosillo,...,181.12,9,0.4,-75.56,1.085,Medium,autumn,Yes,Central America,2013
2218,36974,CA-2012-ZC21910140-41271,2012-12-28,2013-01-04,Standard Class,ZC-219101402,Zuschuss Carroll,Consumer,60610.0,Chicago,...,38.98,3,0.6,-50.67,5.290,Low,winter,Yes,Central US,2012
2219,41315,EG-2014-PM894038-41846,2014-07-26,2014-07-30,Standard Class,PM-894038,Paul MacIntyre,Consumer,NaN,Alexandria,...,25.83,1,0.0,9.03,1.050,Medium,summer,Yes,North Africa,2014

In [60]:
returns_full['Year'] = pd.to_numeric(returns_full['Year'])

In [61]:
yearly_lost_profits = returns_full.groupby(['Year'], as_index=False)['Profit'].sum()

In [62]:
yearly_lost_profits

   Year    Profit
0  2012  17477.26
1  2013   9269.89
2  2014  17510.63
3  2015  17112.97